language: java
sudo: false
cache:
  directories:
    - $HOME/.m2/repository
branches:
    except:
        - gh-pages
jdk:
  - oraclejdk8
  - oraclejdk14
install: /bin/true
script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - jdk_switcher use oraclejdk14
  - mvn test -B
notifications:
  email: false
dist: trusty
